#!/bin/bash
# Script 1: System Identity Report
# Author: Vidhi Ghanekar | Course: OSS

# Variables
STUDENT_NAME="Vidhi Ghanekar"
SOFTWARE_CHOICE="Git"

# System Info
KERNEL=$(uname -r)
USER_NAME=$(whoami)
UPTIME=$(uptime -p)
DATE=$(date)

# For Windows Git Bash (safe fallback)
DISTRO="Windows (Git Bash)"

# Output
echo "================================"
echo "Open Source Audit — $STUDENT_NAME"
echo "================================"
echo "Software: $SOFTWARE_CHOICE"
echo "Kernel  : $KERNEL"
echo "User    : $USER_NAME"
echo "Uptime  : $UPTIME"
echo "Date    : $DATE"
echo "Distro  : $DISTRO"
echo "License : GNU General Public License (GPL)"